
import { api } from "../api";

const employeeAuth = api.injectEndpoints({
    endpoints: (builder) => ({
        addEmployee: builder.mutation({
            query: (values) => ({
                url: '/v2/employee/add_employee',
                method: 'POST',
                body: values,
            }),
        }),

        allEmployee: builder.query({
            query: () => ({
                url: '/v2/employee/find_employees',
                method: 'GET',
            }),
        }),

        updateEmployee: builder.mutation({
            query: ({ id, values }) => ({
                url: `/v2/employee/update_employee/${id}`,
                method: 'PUT',
                body: values,
            }),
        }),

        deleteEmployee: builder.mutation({
            query: (id) => ({
                url: `/v2/employee/delete_employee/${id}`,
                method: 'DELETE',
            }),
        }),
    }),
});

// Correctly exporting the hooks generated by `injectEndpoints`
export const { 
    useAddEmployeeMutation, 
    useAllEmployeeQuery, 
    useUpdateEmployeeMutation, 
    useDeleteEmployeeMutation // added export for deleteEmployee
} = employeeAuth;
