
import { api } from "../api";

const companyAuth = api.injectEndpoints({
    endpoints: (builder) => ({
        addCompany: builder.mutation({
            query: (values) => ({
                url: '/v1/company/add_company',
                method: 'POST',
                body: values,
            }),
        }),

        allCompany: builder.query({
            query: () => ({
                url: '/v1/company/all_company',
                method: 'GET',
            }),
        }),

        updateCompany: builder.mutation({
            query: ({ id, values }) => ({
                url: `/v1/company/update_company/${id}`,
                method: 'PUT',
                body: values,
            }),
        }),

        deleteCompany: builder.mutation({
            query: (id) => ({
                url: `/v1/company/delete_company/${id}`,
                method: 'DELETE',
            }),
        }),
    }),
});

// Correctly exporting the hooks generated by `injectEndpoints`
export const { 
    useAddCompanyMutation, 
    useAllCompanyQuery, 
    useUpdateCompanyMutation, 
    useDeleteCompanyMutation // added export for deleteCompany
} = companyAuth;
